### ISSUE TITLE
Probleem opgelost

### ISSUE THREAD

**Issue by eothein** [thomasaelbrecht/bachelorproef#1]
Beste Thomas
Ik heb je repo gecloned, maar kan het probleem niet reproduceren. Waarschijnlijk heb je de oplossing van @bertvv reeds toegepast.

Mvg Jens Buysse

**Comment by thomasaelbrecht** [comment]
Beste mr. Buysse
Inderdaad ik heb de oplossing van mr. Van Vreckem reeds toegepast. Toch nog bedankt voor je hulp op deze feestdag!
Mvg
Thomas Aelbrecht
